# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designboss.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import random
from time import time


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(700, 317)

        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(30, 100, 631, 121))
        self.textEdit.setObjectName("textEdit")

        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 30, 631, 61))
        self.label.setObjectName("label")

        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 230, 631, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.load = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.load.setObjectName("pushButton")
        self.load.clicked.connect(self.load_previous)
        self.horizontalLayout.addWidget(self.load)

        self.save = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.save.setObjectName("pushButton_2")
        self.save.clicked.connect(self.save_citat)
        self.horizontalLayout.addWidget(self.save)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.load_citat_random("citate.ro")
        self.previous = ""

    def load_citat_random(self, filename):
        with open(filename, "r") as f:
            # Avem sss la sfarsit de fiecare citat in fisier
            citates = f.read().split("sss")
            citat_random = random.choice(citates)
            self.label.setText(citat_random)

    def save_citat(self):
        citat = self.textEdit.toPlainText()
        now = time()
        self.previous = str(now) + ".txt"
        with open(self.previous, "w") as f:
            f.write(citat)

    def load_previous(self):
        with open(self.previous, "r") as file:
            text = file.read()
            self.textEdit.setText(text)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "TextLabel"))
        self.load.setText(_translate("Dialog", "Load"))
        self.save.setText(_translate("Dialog", "Save"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
